### ISSUE TITLE
Why no new build on github release?

### ISSUE THREAD

**Issue by kanyanjp** [BenderBlog/traintime_pda#20]
With the CI configuration in place, downloading from GitHub releases is more convenient compared to joining a group to download the APK.

**Comment by BenderBlog** [comment]
Still some work to do, schedule to release a build at 1.0.0. Also considering remove "reproduce build"...

**Comment by kanyanjp** [comment]
Anything i can help to do with?

**Comment by BenderBlog** [comment]
I schedule to release 1.0.0 in months.
At the moment I released, if fdroid build fails again, I will remove 'reproduce build' support.
Because this app is force on Apple users, Android version will not upload to Chinese appstore.
