### ISSUE TITLE
Failure To Handle Secure Logout From Other Platform

### ISSUE THREAD

**Issue by NanCunChild** [BenderBlog/traintime_pda#23]
When other platform exists this user, app can not handle to securely logout and occupy the user account.
Below are some network flows:

**POST /authserver/login**
`
<header>
	<div class="auth_content_header">
		<div>
			<a id="logoutA" href="/authserver/logout"  class="goLogin lang_text_ellipsis1" title="安全退出">
				<span>安全退出</span>
			</a>
		</div>
	</div>
</header>
<div class="kick-out-content-box">
<div class="kick-out-content">
	<link href="/authserver/xidianNewThemecs0129/static/custom/css/kickout.css?v=20231122.140541" rel="stylesheet"/><div class="tab-content new-tab-content">
		    <div class="ibox-content new-ibox-content">
		        <h3 class="kick-out-title"><span>踢出会话</span></h3>
		        <div>
		            <div class="kick-tips">
						<img src="/authserver/xidianNewThemecs0129/static/custom/images/info-tips.png" class="info-tip-icon" /><div>
							<p class="tip-desc1">当前存在其他用户使用同一账号登录，是否注销其他使用同一账号的用户。</p>
							<p>点击“继续”按钮即注销其他用户。点击“取消”则放弃本次登录，返回到登录页面重新登录。</p>
						</div>
		            </div>
		            <table class="kick_table new-table-kick">
		                <thead>
		                <tr>
		                    <th style="width: 142px;"><span>IP地址</span></th>
		                    <th style="width: 244px;"><span>浏览器</span></th>
		                    <th style="width: 172px;"><span>登录时间</span></th>
		                    <th style="width: 132px;"><span>认证类型</span></th>
		                    </tr>
		                </thead>
						<thead>
		                    <tr>
		                        <td>120.227.35.73</td>
		                        <td title="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.2210.157" >Mozilla/5.0 (X11; Linu...</td>
		                        <td>2024-02-20 08:44:07</td>
		                        <td>免登录</td>
		                        </tr>
		                    </thead>
		            </table>
		        </div>
		        <form method="post" id="continue">
		            <input type="hidden" 
`

**Comment by BenderBlog** [comment]
已经修复，等下个版本就发布。
