### ISSUE TITLE
[Bug] windows export ics

### ISSUE THREAD

**Issue by weekdaycare** [BenderBlog/traintime_pda#24]
windows 测试版生成日历文件出错
windows version: 22631.3155
pda version: 1.1.1+19
![image](https://github.com/BenderBlog/traintime_pda/assets/63026074/df091adc-b649-4da1-bf05-14adecdc8677)

**Comment by weekdaycare** [comment]
https://github.com/BenderBlog/traintime_pda/assets/63026074/4e6c5385-4646-43f2-afa5-6adcfe8221a8

**Comment by BenderBlog** [comment]
构建下载地址: https://github.com/BenderBlog/traintime_pda/actions/runs/8258579154/artifacts/1320827530
看看这个咋样，我尝试用别的库保存

**Comment by weekdaycare** [comment]
可以了👍

**Comment by BenderBlog** [comment]
> 可以了👍

发个录屏可否？我没 windows 设备()

**Comment by BenderBlog** [comment]
Thx
