### ISSUE TITLE
所有版本无法查询水电欠款，以及新版本手机一片空白

### ISSUE THREAD

**Issue by cycode0527** [BenderBlog/traintime_pda#29]
如题，无论是手机上原来就有的旧版本还是电脑上新下载的 watermeter, 都显示水电查询程序故障，打开就是一片白。

第二个问题就是手机上更新到新版本之后，即使显示登陆成功，也只有任务栏的三个图标，主页面一片空白。使用的安装包为 arm64版本，以及 F-droid 提供的版本都试过一次，结果是一样的。手机系统澎湃OS
![a1f5031dfabe6544c9530988713bd051](https://github.com/BenderBlog/traintime_pda/assets/76815699/e54ed6c6-3aa1-44b4-8290-ee2aa7c173ff)

**Comment by BenderBlog** [comment]
仍然建议彻底清除所有数据，然后重新登一下。如问题仍然存在，如果方便，请您发送设置里面的“网络拦截器和日志”（可能有您个人信息，尤其是学号，请注意），如有可能，请通过QQ私信我您的账号密码以让我调试。
最近学校一站式反应十分缓慢，如果您是登录时候等的过久，然后退出重进的话，程序认为已经登录统一认证服务，然后一站式数据没有获取，可能这是大面积崩溃的原因。水电费查不了也是因为登录时候没获取到您的宿舍信息，导致无法计算账号。脑瓜疼.gif
本人最近在忙毕设，可能暂时无法快速修复，请谅解。(先去GPT论文去了)

**Comment by cycode0527** [comment]
> 仍然建议彻底清除所有数据，然后重新登一下。如问题仍然存在，如果方便，请您发送设置里面的“网络拦截器和日志”（可能有您个人信息，尤其是学号，请注意），如有可能，请通过QQ私信我您的账号密码以让我调试。 最近学校一站式反应十分缓慢，如果您是登录时候等的过久，然后退出重进的话，程序认为已经登录统一认证服务，然后一站式数据没有获取，可能这是大面积崩溃的原因。水电费查不了也是因为登录时候没获取到您的宿舍信息，导致无法计算账号。脑瓜疼.gif 本人最近在忙毕设，可能暂时无法快速修复，请谅解。(先去GPT论文去了)

你好，谢谢你抽空回答，但是现在删除所有数据之后有一个新的问题 ，那就是无法登陆了，error提示502,下面是网络截图
![image](https://github.com/BenderBlog/traintime_pda/assets/76815699/fa44d558-36de-44a3-80e2-d78f49bbd1c3)

然后我访问这个红色的连接，提示报错：
<https://ehall.xidian.edu.cn/xsfw/sys/xszsapp/*default/index.do>
![image](https://github.com/BenderBlog/traintime_pda/assets/76815699/da19e958-7806-4252-ad41-01521a7121c7)

所以现在悲催的就是，我在这问题解决之前用不了pda了。但是我印象里好像遇到过这个问题，似乎是一站式无法登陆的原因

**Comment by cycode0527** [comment]
好吧，刚发现我无法登陆的问题解决了，虽然有点奇怪，但是就是无视502, 然后关闭应用，再重新打开就登陆成功了。。。
现在我正在通过日志来在我的浏览器上复现情况

**Comment by BenderBlog** [comment]
> 好吧，刚发现我无法登陆的问题解决了，虽然有点奇怪，但是就是无视502, 然后关闭应用，再重新打开就登陆成功了。。。 现在我正在通过日志来在我的浏览器上复现情况

关于 https://ehall.xidian.edu.cn/xsfw/sys/xszsapp/*default/index.do，这是我获取用户个人信息（主要是宿舍）的信息来源。看来得需要找个新的稳定来源了，这种经常 502 一般都是学校后端卡掉了。疑似电表走的学在西电 learning.xidian.edu.cn ，但我不想用这个。

您要感兴趣可以帮我看看新来源，学工系统应该也能获取。等我忙完毕设我再看()

**Comment by BenderBlog** [comment]
> 好吧，刚发现我无法登陆的问题解决了，虽然有点奇怪，但是就是无视502, 然后关闭应用，再重新打开就登陆成功了。。。 现在我正在通过日志来在我的浏览器上复现情况

请加群 902652582 ，下载该群里最新的构建。登录问题应该修复了。
学工系统的那玩意我当下来了
