### ISSUE TITLE
安卓小部件异常

### ISSUE THREAD

**Issue by weekdaycare** [BenderBlog/traintime_pda#38]
如图
![Screenshot_20240702-103221.png](https://github.com/BenderBlog/traintime_pda/assets/63026074/48e2131c-8d5a-4066-a60f-890f9379e616)

**Comment by BenderBlog** [comment]
版本号看一下，我没记错话曾经修过。

**Comment by weekdaycare** [comment]
1.2.1+213

**Comment by BenderBlog** [comment]
> 1.2.1+213

请加群 902652582 下载该群里面的最新构建：Traintime.PDA.v1.3.0-20240629-ScoreFix.APK

**Comment by BenderBlog** [comment]
确实是在这个版本之后修了下：23c5162d3868f94727b62dc2fefb5c1725680175 & 5ed353742017f260ec7b659596debb49da2ff344 & 78b3baa4d5c96e50000fa3e8efdd33d91fd6cc6a
