### ISSUE TITLE
Maybe a new share method...

### ISSUE THREAD

**Issue by NanCunChild** [BenderBlog/traintime_pda#50]
As Now, the class table file sharing page is based on *Android original method*, which is not very adapted with some machine such like HUAWEI, Xiaomi and so on. It can not even show a complete text and it has few sharing option.
I strongly recommand to change a new page(method) of sharing to solve these problems from its root.
Thank you superbart, love you forever. 

![Screenshot_20240922_012632_android](https://github.com/user-attachments/assets/6885ae13-c8db-4658-99c9-db865052fe6f)

**Comment by BenderBlog** [comment]
One priciple: NO SERVER!

**Comment by NanCunChild** [comment]
I just mean that another lib-supported sharing page. The name is extend share.

**Comment by BenderBlog** [comment]
I add a way to open erc file to the program.
